# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
# Clone the install rsdic repo
    - git clone https://github.com/kedartatwawadi/rsdic
    - cd rsdic
    - ./waf configure
    - ./waf
    - sudo ./waf install
    - cd ..

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  
